# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iran_list.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name')),
                ('name_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pub', 'Published'), ('rej', 'Rejected')], default='pub', max_length=3, verbose_name='Status')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Versions',
                'verbose_name': 'Version',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='English Name')),
                ('name_fa', models.CharField(max_length=255, verbose_name='Persian Name')),
                ('website', models.URLField(unique=True, verbose_name='Website Url')),
                ('status', models.CharField(choices=[('pen', 'Pending'), ('pub', 'Published'), ('rej', 'Rejected')], default='pen', max_length=3, verbose_name='Status')),
                ('average_p_rate', models.FloatField(default=0.0, verbose_name='Average People Rate')),
                ('average_e_rate', models.FloatField(default=0.0, verbose_name='Average Editor Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handler', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_editor', models.BooleanField(default=False, verbose_name='Is Editor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=1, verbose_name='Rate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.Product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.Profile', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Versions',
                'verbose_name': 'Version',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Types',
                'verbose_name': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pen', 'Pending'), ('pub', 'Published'), ('rej', 'Rejected')], default='pen', max_length=3, verbose_name='Status')),
                ('version_code', models.IntegerField()),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='English description')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Persian description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('android_app', models.URLField(blank=True, null=True, verbose_name='Android App')),
                ('ios_app', models.URLField(blank=True, null=True, verbose_name='iOS App')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('extra_url', models.URLField(blank=True, null=True, verbose_name='Extra Url')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year Created')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='Employees Count')),
                ('logo', models.ImageField(blank=True, default='products/logo/default.png', null=True, upload_to='products/logo', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, default='products/banner/default.png', null=True, upload_to='products/banner', verbose_name='Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('editor', models.ForeignKey(on_delete=models.SET(iran_list.products.models.get_sentinel_user), related_name='versions', to='products.Profile', verbose_name='Editor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.Product', verbose_name='Product')),
                ('responder', models.ForeignKey(on_delete=models.SET(iran_list.products.models.get_sentinel_user), related_name='responded_versions', to='products.Profile', verbose_name='Responder')),
            ],
            options={
                'verbose_name_plural': 'Versions',
                'verbose_name': 'Version',
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.Type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(iran_list.products.models.get_sentinel_user), related_name='added_products', to='products.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.Version'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Profile', verbose_name='User'),
        ),
    ]
