# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import iran_list.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161019_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(iran_list.products.models.get_sentinel_user), related_name='responded_versions', to='products.Profile', verbose_name='Responder'),
        ),
    ]
