# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161019_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='products/banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='version',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/logo', verbose_name='Logo'),
        ),
    ]
