# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161019_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
