# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ranking',
            field=models.FloatField(default=0.0, verbose_name='Ranking'),
        ),
    ]
